### PR TITLE
Add Korean's missing translation

### PR DESCRIPTION
**Pull request by nnnlog**
### Purpose and Effect of This Pull Request

Add Korean's missing translation

### Testing
Complete test

### CODE REVIEW

**Comment by Johnmacrocraft** [comment]
You could still merge this, but I'll update it again according to official PocketMine-MP translation (I updated it according to Minecraft: Java Edition translation, it was pretty hard work).

**Comment by nnnlog** [comment]
@Johnmacrocraft 텔레그램 좀 봐주세요

**Comment by nnnlog** [comment]
@Johnmacrocraft 리뷰좀요(병합되려면 필요한듯)

**Comment by jdongel2004** [comment]
맨 처음에 Johnmacrocraft/nnnlog 번역 도움. 만 고치신줄 알고 깜놀 ㅋㅋㅋ

**Comment by nnnlog** [comment]
@jdongel2004 ㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by Johnmacrocraft** [comment]
@nnnlog 평가 드렸습니다.

**Pull request merged**
