### PR TITLE
Update SessionManager.php

### PR DESCRIPTION
**Pull request by flayzer**

### CODE REVIEW

**Comment by DerddyDert** [comment]
@flayzer have you stopped by our discord yet?

**Comment by flayzer** [comment]
@DerddyDert What kind of strife?

**Comment by flayzer** [comment]
@xISRAPILx Updates are needed to ensure that they are there, and not needed!

**Comment by DerddyDert** [comment]
@flayzer our discord. https://discordapp.com/invite/WrKzRNn

**Comment by xISRAPILx** [comment]
pls close @DerddyDert 
it stupid pr

**Pull request closed without merging**
