### PR TITLE
Fixed PHP Threads Error | PHP 7.2 && PHP 7.0

### PR DESCRIPTION
**Pull request by InspectorGadget**
### Purpose and Effect of This Pull Request
I've fixed a PHP Thread Error for both PHP 7.0 and also PHP 7.2 (future). This error can cause RakLib crash due to some symbolic errors. 

### Testing

I've reproduced this error many times and also have tested this fix.

Before Fixing:

`[20:47:38] [Server thread/INFO]:
 
  _____            _               _____
 / ____|          (_)             |  __ \
| |  __  ___ _ __  _ ___ _   _ ___| |__) | __ ___
| | |_ |/ _ \ '_ \| / __| | | / __|  ___/ '__/ _ \
| |__| |  __/ | | | \__ \ |_| \__ \ |   | | | (_) |
 \_____|\___|_| |_|_|___/\__, |___/_|   |_|  \___/
                          __/ |
                         |___/
 
        Version: 1.1dev (0d664ff)
        Client Version: v1.1.0,v1.1.1,v1.1.2,v1.1.3,v1.1.4,v1.1.5,v1.1.7
        PHP Version: 7.2.0RC2
        OS: WINNT
        This core is maintained by GenisysPro (https://github.com/GenisysPro)
        Discord Group chat: https://discord.gg/WrKzRNn
        Chatroom on QQ: 559301590
        Welcome to donate us on QQ: 1912003473
 
[20:47:38] [Server thread/INFO]: Loading properties and configuration...
[20:47:38] [Server thread/WARNING]: Online mode has been turned off in server.properties
[20:47:38] [Server thread/WARNING]: Xbox Live authentication is disabled.
[20:47:38] [Server thread/INFO]: Selected English (eng) as the base language
PHP Warning:  Declaration of pocketmine\Worker::start(int $options = PTHREADS_INHERIT_ALL) should be compatible with Thread::start(?int $options = NULL) in C:\Users\RTG\Documents\Work Folder\GenisysPr
o\src\pocketmine\Worker.php on line 115
 
Warning: Declaration of pocketmine\Worker::start(int $options = PTHREADS_INHERIT_ALL) should be compatible with Thread::start(?int $options = NULL) in C:\Users\RTG\Documents\Work Folder\GenisysPro\src
\pocketmine\Worker.php on line 115
[20:47:38] [Server thread/WARNING]: Debugging assertions are enabled, this may impact on performance. To disable them, set `zend.assertions = -1` in php.ini.
[20:47:38] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[20:47:38] [Server thread/INFO]: GenisysPro is distributed under the GPL License version 3 and later
[20:47:38] [Server thread/INFO]: Loading recipes...
[20:47:38] [Server thread/INFO]: Loading resource packs...
[20:47:38] [Server thread/INFO]: Preparing level "world"
[20:47:38] [Server thread/INFO]: Preparing level "nether"
[20:47:38] [Server thread/INFO]: Preparing level "ender"
[20:47:38] [Server thread/INFO]: Starting GS4 status listener
[20:47:38] [Server thread/INFO]: Setting query port to 19132
[20:47:38] [Server thread/INFO]: Query running on 0.0.0.0:19132
[20:47:38] [Server thread/INFO]: Default game type: Survival Mode
[20:47:38] [Server thread/INFO]: Done (0.589s)! For help, type "help" or "?"`

After Fixing:

`[20:48:56] [Server thread/INFO]:
 
  _____            _               _____
 / ____|          (_)             |  __ \
| |  __  ___ _ __  _ ___ _   _ ___| |__) | __ ___
| | |_ |/ _ \ '_ \| / __| | | / __|  ___/ '__/ _ \
| |__| |  __/ | | | \__ \ |_| \__ \ |   | | | (_) |
 \_____|\___|_| |_|_|___/\__, |___/_|   |_|  \___/
                          __/ |
                         |___/
 
        Version: 1.1dev (0d664ff)
        Client Version: v1.1.0,v1.1.1,v1.1.2,v1.1.3,v1.1.4,v1.1.5,v1.1.7
        PHP Version: 7.2.0RC2
        OS: WINNT
        This core is maintained by GenisysPro (https://github.com/GenisysPro)
        Discord Group chat: https://discord.gg/WrKzRNn
        Chatroom on QQ: 559301590
        Welcome to donate us on QQ: 1912003473
 
[20:48:56] [Server thread/INFO]: Loading properties and configuration...
[20:48:56] [Server thread/WARNING]: Online mode has been turned off in server.properties
[20:48:56] [Server thread/WARNING]: Xbox Live authentication is disabled.
[20:48:56] [Server thread/INFO]: Selected English (eng) as the base language
[20:48:56] [Server thread/WARNING]: Debugging assertions are enabled, this may impact on performance. To disable them, set `zend.assertions = -1` in php.ini.
[20:48:56] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[20:48:56] [Server thread/INFO]: GenisysPro is distributed under the GPL License version 3 and later
[20:48:56] [Server thread/INFO]: Loading recipes...
[20:48:56] [Server thread/INFO]: Loading resource packs...
[20:48:56] [Server thread/INFO]: Preparing level "world"
[20:48:56] [Server thread/INFO]: Preparing level "nether"
[20:48:56] [Server thread/INFO]: Preparing level "ender"
[20:48:56] [Server thread/INFO]: Starting GS4 status listener
[20:48:56] [Server thread/INFO]: Setting query port to 19132
[20:48:56] [Server thread/INFO]: Query running on 0.0.0.0:19132
[20:48:56] [Server thread/INFO]: Default game type: Survival Mode
[20:48:56] [Server thread/INFO]: Done (0.555s)! For help, type "help" or "?"`

Thanks

### CODE REVIEW

**Comment by SuperXingKong** [comment]
It is a new feature of php7.2. If you use it on php7.0, it will cause a crash.

**Comment by InspectorGadget** [comment]
How sure are you that it'll break on PHP 7.0? Have you tested?

**Comment by SuperXingKong** [comment]
@InspectorGadget This is obvious...

**Comment by InspectorGadget** [comment]
I think you still need to prove before closing

**Comment by SuperXingKong** [comment]
ok

**Comment by SuperXingKong** [comment]
I have tested it. I am sure that it didn't work. So can I close this pr?

**Comment by CortexPE** [comment]
It's already on the 1.2 branch @InspectorGadget https://github.com/GenisysPro/GenisysPro/commit/c4d686f663634d1a0d82c7127d6d56d8423a28f6 xD
@SuperXingKong or @InspectorGadget can close this PR now...
Someone just need to merge the changes from the master branch to the php7.2 branch to update it

**Comment by InspectorGadget** [comment]
Can I see the log or something?

**Comment by InspectorGadget** [comment]
Ok @CortexPE

**Comment by SuperXingKong** [comment]
Also thank @InspectorGadget for your work

**Pull request closed without merging**
