### PR TITLE
Update command, for players

### PR DESCRIPTION
**Pull request by flayzer**
Hide command for players, not worth.
line 748: if($this->hasPermission($command->getPermission())){

### CODE REVIEW

**Comment by An0ther1337** [comment]
@flayzer count($count)? $count is int...

**Comment by flayzer** [comment]
@ivan691 thanks

**Comment by flayzer** [comment]
@An0ther1337 additionally

**Comment by Frago9876543210** [comment]
Everything worked well. Why change this?

**Comment by xISRAPILx** [comment]
ниже есть коммит, а вот коунт тут нахуя?

**Comment by xISRAPILx** [comment]
-1

**Comment by xISRAPILx** [comment]
@DerddyDert dublicate + exists not needed code...

**Pull request closed without merging**
