### PR TITLE
Update to PHP7.2

### PR DESCRIPTION
**Pull request by AppleDevelops**
Removes backwards compatibility for PHP7.0 and 7.1, I'm only creating this PR due to EnderCrate (hosting) using this software but we force 7.2 like PocketMine. So if you want happy people, accept this pr.

### CODE REVIEW

**Comment by DerddyDert** [comment]
@AppleDevelops Cool, thanks man. Where can 7.2 be acquired?

**Comment by AppleDevelops** [comment]
There are bin folders for it on dktapp's [Twitter](twitter.com/dktapps) or I can provide the links.

[Windows](ci.appveyor.com/api/buildjobs/5hw216vpuv5cyefp/artifacts/php-7.2.0RC1-Win32-VC15-x64.zip)

[Linux](https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz)

**Comment by DerddyDert** [comment]
@AppleDevelops , @CortexPE is the new sheriff in town so I'll let him handle this PR. We are cleaning house and restructuring at the moment.

**Comment by Frago9876543210** [comment]
@AppleDevelops Is there a binary for android?

**Comment by AppleDevelops** [comment]
You can build your own, on PMMP’s build scripts. And thanks, GenisysPro will be EnderCrate tonight.

**Comment by DerddyDert** [comment]
@AppleDevelops  what's EnderCrate?

**Comment by AppleDevelops** [comment]
Server hosting @DerddyDert

**Comment by fuyutsuki** [comment]
php 7.2 is fast, I agree 👍

**Comment by DerddyDert** [comment]
@AppleDevelops ah cool, ill check it out. Thanks man.

**Pull request merged**
