### PR TITLE
Minecart can move more fluent

### LINKED ISSUE #682: please, add setButtonText function.
please, add this function.

(this code is from Nukkit)
public void setButtonText(String text) {
this.buttonText = text;
this.setDataProperty(new StringEntityData(Entity.DATA_INTERACTIVE_TAG, this.buttonText));
}

### PR DESCRIPTION
**Pull request by larryTheCoder**
### The following Pull Request will have these changes:
- Minecarts can move more fluent
- Minecart and boats can have collisions
- Added interaction feature for minecart
- fix #682

### Testing
This pull request had been tested including:
- Minecart movement
- Collisions
- Interaction

### CODE REVIEW

**Comment by Leo3418** [comment]
Definitely, this pull request needs very thorough and strict test before being merged.

**Comment by larryTheCoder** [comment]
@Leo3418 Of course, There a note that saying `Do not merge` I am currently download PHP library. I will inform @DerddyDert next 9 Hours :D

**Comment by xISRAPILx** [comment]
Oh, good job

**Comment by larryTheCoder** [comment]
@Leo3418 This minecart had been tested. Test it second time maybe there several errors before we merge this

**Comment by larryTheCoder** [comment]
ARGH

**Comment by larryTheCoder** [comment]
Anyone merge? Its completed

**Comment by DerddyDert** [comment]
@larryTheCoder why did you need to change a million files for this pr?

**Comment by DerddyDert** [comment]
You also need to resolve conflicts

**Comment by larryTheCoder** [comment]
Sorry if theres a millions changes. I cant reformat each files. Eg. Player.php formatting are diffrent than others. Genisys will need a propper fomatting guide. I will solve conflicts later.

**Comment by xISRAPILx** [comment]
update you fork and fix errors

**Comment by larryTheCoder** [comment]
@xISRAPILx Done 😄

**Comment by Frago9876543210** [comment]
pls backup you changes and update fork

**Comment by CortexPE** [comment]
pls fix formatting... :/

**Comment by larryTheCoder** [comment]
This pull request are not ready yet to merge.

**Pull request closed without merging**
