### PR TITLE
Add some sounds from a pmmp pull request

### PR DESCRIPTION
**Pull request by poustmal**
This adds some missing sounds from this pull request: https://github.com/pmmp/PocketMine-MP/pull/1064
I tried to add the changes to genisys pro,but i can't add them all.

### CODE REVIEW

**Comment by DerddyDert** [comment]
You just took a whole pmmp file and dropped it in?

**Comment by AppleDevelops** [comment]
Copying and pasting failed 😆

**Comment by DerddyDert** [comment]
@AppleDevelops hahaha he is busted but you don't have to run it in man.lol

**Comment by poustmal** [comment]
I copied the changed lines in pr and added here,but with upload

**Comment by DerddyDert** [comment]
I was talking about src/pocketmine/item/ChestInventory.php that file doesn't exist there. Plus it even says pocketmine. 😝

**Comment by poustmal** [comment]
ops,yes..

**Comment by DerddyDert** [comment]
Can you remove that file?

**Comment by DerddyDert** [comment]
Why you close it?

**Comment by erkam2002** [comment]
Bruh

**Comment by poustmal** [comment]
The chestinvetory didn't uploaded

**Comment by poustmal** [comment]
but I ll make better pr

**Pull request closed without merging**
