### PR TITLE
I think this is no longer exist!

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by Frago9876543210** [comment]
@erkam2002 Ok, but then you need to completely remove it from the core.

**Comment by erkam2002** [comment]
I removed it in other pr

**Comment by DerddyDert** [comment]
@erkam2002 why not make it in one PR? @Frago9876543210 can you check his second PR so we can merge them?

**Comment by Leo3418** [comment]
I'm closing this because #397 includes change in this pull request.

**Comment by DerddyDert** [comment]
@Leo3418  good call. I was wondering if that was the case but I didn't have a chance to compare.

**Pull request closed without merging**
