### PR TITLE
Fixed raklib crash

### PR DESCRIPTION
**Pull request by SuperAdam47**

### CODE REVIEW

**Comment by Frago9876543210** [comment]
This remove kick message

**Comment by MasterOfTheRealm** [comment]
@SuperAdam47 Can you please explain how you came to this conclusion? Seriously... please explain what your PR does and your reasons why, and whether you have tested it or not. Else this PR will be closed!

**Comment by SuperAdam47** [comment]
Can you try it yourself?

**Comment by MasterOfTheRealm** [comment]
Tell me how the crash is caused. you didn't even bother explaining so idek what this will be fixing

**Comment by ivan691** [comment]
Removing this line will return a bug with displaying messages when kick from the server. Besides, I have no problems after this commit.

**Comment by SuperAdam47** [comment]
sorry this line of code is coming out due to my plugin error.

**Comment by SuperXingKong** [comment]
#873 Serious...

**Comment by MasterOfTheRealm** [comment]
Uhhh... actually i don't think this fixes that at all... now again the disconnect messages are messed up by merging this :'(

**Pull request merged**
