### PR TITLE
lol, sorry

### LINKED ISSUE #850: help
Hello. The help 2 command does not work. 
outputs information from help 1

2017-08-26 [16:53:12] [Server thread/INFO]: -----Server information-----
2017-08-26 [16:53:12] [Server thread/INFO]: This server is running GenisysPro-1.1dev (0000000) LlamaSpit
2017-08-26 [16:53:12] [Server thread/INFO]: PHP version: 7.0.22
2017-08-26 [16:53:12] [Server thread/INFO]: API: 3.0.1
2017-08-26 [16:53:12] [Server thread/INFO]: Target client: Minecraft PE v1.1.0,v1.1.1,v1.1.2,v1.1.3,v1.1.4,v1.1.5
2017-08-26 [16:53:12] [Server thread/INFO]: Protocol version: 113

### PR DESCRIPTION
**Pull request by xISRAPILx**
### Purpose and Effect of This Pull Request
fix #850 

### Testing
yes

### CODE REVIEW

**Comment by xpyctumo** [comment]
This is not necessary to do.

**Comment by DerddyDert** [comment]
@xpyctumo why not?

**Comment by xpyctumo** [comment]
@DerddyDert json can be only string

**Comment by xISRAPILx** [comment]
@xpyctumo No, sometimes it gives an object or int

**Pull request closed without merging**
