### PR TITLE
Correcting crash when getting the name of the world when it is unloaded.

### PR DESCRIPTION
**Pull request by xISRAPILx**
### Purpose and Effect of This Pull Request
Correcting crash when getting the name of the world when it is unloaded.

### Testing
Yes! All nice work.

### CODE REVIEW

**Comment by xISRAPILx** [comment]
FIXED!
image

**Comment by SuperXingKong** [comment]
The hack of getName() will be removed soon. Stll can't negative you did a good job

**Comment by TheAz928** [comment]
I don't see any good changes :/ Just spaces and brackets edition. And you can get unloaded level name by just accessing their level.dat,
when you uncompress nbt of a level.dat, you can get level name by doing $nbt->LevelName->getValue();

**Comment by TheAz928** [comment]
@DerddyDert Maybe this is the code that your looking for `$nbt = new NBT(NBT::BIG_ENDIAN);
		$nbt->readCompressed(file_get_contents(Server::getInstance()->getDataPath() . "worlds/" . $levelFolderName . "/level.dat"));
		$levelData = $nbt->getData();
		if($levelData->Data instanceof CompoundTag){
			$nbtData = $levelData->Data;
		}else{
			throw new LevelException("Invalid level.dat");
		}
		$levelName = $nbtData->LevelName->getValue();`

**Pull request merged**
