### PR TITLE
Create genisys_zho.yml

### PR DESCRIPTION
**Pull request by edwinyoo44**

### CODE REVIEW

**Comment by lightda104530** [comment]
嗨~夜喵owo
這應該是pocketmine.yml的繁化對吧?

**Comment by DerddyDert** [comment]
What is zho????

**Comment by lightda104530** [comment]
@DerddyDert zho is traditional chinese

**Comment by edwinyoo44** [comment]
@lightda104530 YES

**Comment by lightda104530** [comment]
@edwinyoo44  但是命名錯誤...

**Comment by lightda104530** [comment]
it should be pocketmine_zho.yml OuO b

**Comment by edwinyoo44** [comment]
@lightda104530  哈哈，複製錯檔案

**Comment by lightda104530** [comment]
好囉~我確定囉:D

**Comment by DerddyDert** [comment]
@lightda104530 so cool. Its traditional or ancient Chinese? I tried to study accident Chinese when I was in Korea...

**Pull request merged**
