### PR TITLE
Add sound on spawnLightning and sendLightning

### PR DESCRIPTION
**Pull request by armagadon159753**
### Testing

I cant summon lightning 😬

### CODE REVIEW

**Comment by erkam2002** [comment]
Looks good

**Comment by armagadon159753** [comment]
Why?
`$chunk = $this->getChunk($pos->x >> 4, $pos->z >> 4, false);`

**Comment by erkam2002** [comment]
yes

**Comment by armagadon159753** [comment]
I have no idea why no working with that

**Comment by xISRAPILx** [comment]
-1... It's not his sounds.

**Comment by TheAz928** [comment]
Explode sound is for tnt? or I'm wrong?

**Comment by armagadon159753** [comment]
I sure  about that or otherwise I can use this
LevelSoundEventPacket const SOUND_THUNDER = 44

**Comment by TheAz928** [comment]
Yes broadcast LevelEventPacket

**Comment by erkam2002** [comment]
But i think lighting make a explode sound but before it come on ground another sound

**Comment by MasterOfTheRealm** [comment]
@armagadon159753 Tested This And It Does Not Work.

**Pull request closed without merging**
