### PR TITLE
pls, Update jpn.ini

### PR DESCRIPTION
**Pull request by shoki-3738**

### CODE REVIEW

**Comment by shoki-3738** [comment]
How about trying other languages in the same way?
shoki-3738[IP: xxx.xxx.xxx.xxx | Port: xxxxx] [ClientID: xxxxxxxxxxxxxx]...

**Comment by lightda104530** [comment]
?

**Comment by shoki-3738** [comment]
Here, "[IP: xxx.xxx.xxx.xxx | Port: xxxxx]"

**Comment by shoki-3738** [comment]
Now:
pocketmine.player.logIn= {%0}[/{%1}:{%2}] [ClientID: {%3}] logged in with entity id {%4} at ({%5}, {%6}, {%7}, {%8})

My plan:
pocketmine.player.logIn= {%0}[IP:{%1} | Port: {%2}] [ClientID: {%3}] logged in with entity id {%4} at ({%5}, {%6}, {%7}, {%8})

**Pull request merged**
