### PR TITLE
Fix #782 - Disappearing FloatingTextParticle bug

### LINKED ISSUE #782: FloatingParticle bug :(
#### Platform information

* Git commit:

* PHP binary version:

* Server OS:

* Game client:

#### Crash dump, back trace, memory dumps, plugins list or other files (if any)

```

```

### PR DESCRIPTION
**Pull request by CortexPE**
### Purpose and Effect of This Pull Request
This PR Makes FloatingTextParticle.php spawn an Invisible player Instead of an ItemEntity (which... Despawns after a few mins)

### Testing
use this code: (or any other Floating Text plugin you have)
```php
// This code was taken from MY "TESTERPLUGIN" Which I use for short tests and is Written on Notepad++... (Too Lazy to open PHPStorm just to code short stuff.)
// $p = A player....
$level = $p->getLevel();
$pos = $p->getPosition();
$level->addParticle(new FloatingTextParticle($pos->add(0.5, 0.0, 0.5),"LOL",  "lolcow"));
// This code was taken from MY "TESTERPLUGIN" Which I use for short tests and is Written on Notepad++... (Too Lazy to open PHPStorm just to code short stuff.)
```

### CODE REVIEW

**Comment by CortexPE** [comment]
Happy 100 Forks GenisysPro!

**Comment by AppleDevelops** [comment]
Nice PR, wonder where you copied it 🤔

**Comment by CortexPE** [comment]
CREDITS: Originally from https://github.com/pmmp/PocketMine-MP/pull/1205
Credits to @mal0ne-23 for the original PR ;)

**Comment by xISRAPILx** [comment]
It used to be so ... @AppleDevelops He returned it.

**Comment by xISRAPILx** [comment]
Previously, this part looked exactly like that. @AppleDevelops

**Pull request merged**
