### PR TITLE
Stupid thing. Nobody needs it. After it there were many problems.

### PR DESCRIPTION
**Pull request by xISRAPILx**

### CODE REVIEW

**Comment by MasterOfTheRealm** [comment]
is this where it checks perms before sending available commands? @xISRAPILx

**Comment by xISRAPILx** [comment]
Yes. It hides commands if you do not have the rights. @MasterOfTheRealm

**Comment by SuperXingKong** [comment]
It's hard to say whether it was right or not..

**Comment by SuperXingKong** [comment]
But I recommand merge this pr

**Comment by DerddyDert** [comment]
@CortexPE is it still being used for another purpose because all commands show to everyone currently.

**Comment by erkam2002** [comment]
This is not useless its like vanille if you play on singleplayer

**Comment by xISRAPILx** [comment]
#829

**Pull request closed without merging**
