### PR TITLE
Update Snowball.php

### PR DESCRIPTION
**Pull request by DerddyDert**
They are small. 16 is too low. 64 is better.

### CODE REVIEW

**Comment by armagadon159753** [comment]
why not.
If you do it for the SnowBall, do the same for the EnderPearl?
^~^

**Comment by erkam2002** [comment]
No!!! 16 is default!!!! dont change this

**Comment by armagadon159753** [comment]
@erkam2002 I confirm this is not a good idea as I tested and when I throw a snowball are number returns to 16

**Comment by DerddyDert** [comment]
It was just a though exercise, thats why I never merged it. We need to consider things to level the playing field between win10 and mobile devices.

**Pull request closed without merging**
