### PR TITLE
Fix Levitation effect

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by MasterOfTheRealm** [comment]
Please Explain What It Does And Have You Tested It?

**Comment by erkam2002** [comment]
If levitation ends you will get kicked or flaged by anti-cheat

**Comment by erkam2002** [comment]
MERGE!!!

**Comment by erkam2002** [comment]
?!

**Comment by erkam2002** [comment]
This code is tested please merge

**Comment by Leo3418** [comment]
To avoid more spam messages, I have limited conversations to collaborators. Please do not send useless comments.

**Pull request merged**
