### PR TITLE
Title Fade error fixed and Beacon update

### PR DESCRIPTION
**Pull request by Prisane**
### Description
Fixed the title error and I made beacon stability update

### Reason to modify
It is the best way. No need for BeaconDelayedTask. So the beacon has to be updated.

### Tests & Reviews
I have tested the code and it works.

### CODE REVIEW

**Comment by SuperXingKong** [comment]
I will test it;)

**Comment by Prisane** [comment]
Thanks.

**Comment by caspervanneck** [comment]
its copyed of pmmp maby not merge it ?

**Comment by caspervanneck** [comment]
or a other fork

**Comment by Prisane** [comment]
Everything is open source. The important thing is the stability work.

**Comment by SuperXingKong** [comment]
Have you tested it? Did beacon work well?

**Comment by Prisane** [comment]
Yes, It worked without any problems.

**Comment by SuperXingKong** [comment]
Great~ Thank you!

**Pull request merged**
