### PR TITLE
Fix block break

### LINKED ISSUE #290: Block's breaking animation don't seeing

### PR DESCRIPTION
**Pull request by xISRAPILx**
### Purpose and Effect of This Pull Request
Fix #290 and #637 

### Testing
image

### CODE REVIEW

**Comment by xISRAPILx** [comment]
@Leo3418 @DerddyDert @Frago9876543210

**Comment by xISRAPILx** [comment]
Don't merge

**Comment by Leo3418** [comment]
Why not?

**Comment by xISRAPILx** [comment]
TODO: Add sound @Leo3418

**Comment by xISRAPILx** [comment]
Wait... @Leo3418

**Comment by xISRAPILx** [comment]
@Leo3418 Thank's!

**Comment by xISRAPILx** [comment]
I do not know how to add ... BLOCK_BREAK_SOUND does not work. Merge. I'll do it later. @Leo3418

**Comment by xISRAPILx** [comment]
You know how to add breaking sound? Break sound exists.

_Отправлено с моего Samsung SM-T531 с помощью [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Leo3418** [comment]
> You know how to add breaking sound? Break sound exists.

I think that should be something similar to https://github.com/GenisysPro/GenisysPro/commit/332f028dc5e5184da0ee6b2f680185303dcc6cd1.

**Pull request merged**
