### PR TITLE
Update Player.php

### PR DESCRIPTION
**Pull request by RateekMCPE**
Fix...

### CODE REVIEW

**Comment by DerddyDert** [comment]
@RateekMCPE can you explain how this fixes #188 ?

**Comment by RateekMCPE** [comment]
@DerddyDert No fix #118, Event cancellation serves no purpose

**Comment by MasterOfTheRealm** [comment]
@RateekMCPE won't that remove anti movement cheat bypass?

**Comment by SuperXingKong** [comment]
It will break Anti-movement-cheats >_<

**Comment by DerddyDert** [comment]
@SuperXingKong  needs to double check this one.

**Comment by DerddyDert** [comment]
Oh that's fast

**Comment by SuperXingKong** [comment]
Really?

**Comment by SuperXingKong** [comment]
In this way, the 'allow-movement-cheats' option in config won't work

**Comment by MasterOfTheRealm** [comment]
Yes exactly

**Comment by DerddyDert** [comment]
No I typed you need to double check it exactly 2 seconds before you close it haha. You were correct @SuperXingKong

**Comment by DerddyDert** [comment]
And I meant double check @RateekMCPE code

**Pull request closed without merging**
