### PR TITLE
Makes Japanese section understandable by Japanese people

### PR DESCRIPTION
**Pull request by TreatHacker**
### Purpose and Effect of This Pull Request

@Takesikaityo used Google Translate for README.md so I re-translated Japanese section.
Only effects README.md in this repo.    
_I'm sorry for similar type of PRs twice._

### Testing

No test for php files required.    
I have already checked that Markdown will be rendered correctly on my PC.

---
Just ignore above.
---
@Takesikaityo おいあくしろよGoogle翻訳名人()さん    
Issue見に行く前にやることあるんじゃねーのか? あ?    
早く仕事やれや

### CODE REVIEW

**Comment by Leo3418** [comment]
🤦‍♂️

**Comment by TreatHacker** [comment]
@DerddyDert Can you please ask other author(s) to review this PR?     
@Takesikaityo is sabotaging review of this PR.

**Comment by wakame0731** [comment]
I'm Japanese. This translation is good. Old translation cannot read fluently. It has sentence problem.

**Comment by nao20010128nao** [comment]
what the...

**Comment by TreatHacker** [comment]
@Leo3418 Thank you so much!

**Pull request merged**
