### PR TITLE
Update Player.php for ItemFrame watch #615

### PR DESCRIPTION
**Pull request by SuperKali**

### CODE REVIEW

**Comment by SuperKali** [comment]
#615

**Comment by Leo3418** [comment]
What does this pull request do? Allows only OPs to drop item from an item frame?

**Comment by SuperKali** [comment]
Yes only op

**Comment by SuperKali** [comment]
Normal players can move items within the item frame

**Comment by Leo3418** [comment]
Rejected:  
Non-op players cannot even break any item frame, unless they break the block where the frame is attached onto.
What's more, you need to follow the original code format, especially indentation. Your pull request description is very poor, I have to ask you if I want to know what your commit will do.

**Pull request closed without merging**
