### PR TITLE
Fix issue #333

### PR DESCRIPTION
**Pull request by G2PCraft**
Maybe this can fix issue #333

### CODE REVIEW

**Comment by AppleDevelops** [comment]
Stop making maybe fix, you either fix it or you don’t

**Comment by AppleDevelops** [comment]
If you aren’t sure then don’t copy it genius

**Comment by Rateek** [comment]
@AppleDevelops +1 loul

**Comment by DerddyDert** [comment]
@G2PCraft of me know if you test it.

**Comment by G2PCraft** [comment]
Okay.

**Comment by DerddyDert** [comment]
@AppleDevelops you tryin to help or you just giving him a hard time? Feel free to join us if you ever get bored with all your other projects.

**Pull request closed without merging**
