### PR TITLE
PHPStorm inspections

### PR DESCRIPTION
**Pull request by AppleDevelops**
### Description

To make your software not look shittier
WIP

### Reason to modify

It makes your stuff look better

### Tests & Reviews

I have tested the code and it works.

### CODE REVIEW

**Comment by AppleDevelops** [comment]
nononono don't request a review from Bajan, dudes a fake dev and hates me

**Comment by DerddyDert** [comment]
Hahaha he likes your PR

**Comment by AppleDevelops** [comment]
@DerddyDert He makes DDoS threats, says he knocked them offline when they crash, and blocks them on Twitter after starting drama.

**Comment by DerddyDert** [comment]
@AppleDevelops thanks again. Bajan keeps it professional on genisyspro so nothing to worry about here.

**Comment by Frago9876543210** [comment]
@AppleDevelops What is the name of this style of code? And where it can be replaced in PHP Storm?

**Comment by AppleDevelops** [comment]
@Frago9876543210 It’s a custom one, I’ll provide a download for it soon.

**Comment by Frago9876543210** [comment]
@AppleDevelops okey

**Comment by DerddyDert** [comment]
@SuperXingKong yeah it's really nice

**Pull request merged**
