### PR TITLE
Trying to add ender world

### PR DESCRIPTION
**Pull request by Frago9876543210**
### Description
I added ender.

### Reason to modify
Also, I changed several files with warnings that phpstorm has issued. I apologize for my code style.

### Tests & Reviews
All tested, but I have bugs with chunks.
alt text

### CODE REVIEW

**Comment by DerddyDert** [comment]
Looks like you did a great job but @SuperXingKong Will have to review this one.

**Comment by lightda104530** [comment]
WoW great job

**Comment by MasterOfTheRealm** [comment]
Well done!

**Comment by DerddyDert** [comment]
We need to isolate the critical error from the last few commits first. #176

**Comment by DerddyDert** [comment]
@Frago9876543210 please join us in discord https://discord.gg/WrKzRNn

**Comment by MasterOfTheRealm** [comment]
Which commit caused that error?

**Comment by DerddyDert** [comment]
Ummm maybe when u added more mobs? I was just heating up on some llamas. @MasterOfTheRealm

**Comment by MasterOfTheRealm** [comment]
@DerddyDert you can look at what i changed. Also i got that error before my commits took place.

**Comment by DerddyDert** [comment]
@MasterOfTheRealm I didn't but is not going to be a big issue

**Comment by Frago9876543210** [comment]
I upload video
https://youtu.be/UfU0gHaNZy0

**Comment by SuperXingKong** [comment]
How about create a branch for end?

**Comment by DerddyDert** [comment]
@SuperXingKong I don't think he realized what you recommended. Plus he cannot write. Can you take his code and start an official Ender branch? His code has been tested and works if you have a plugin to change levels/worlds but just needs a portal.

**Comment by DerddyDert** [comment]
@Frago9876543210 :1st_place_medal:

**Pull request merged**
