### PR TITLE
update MainLogger.php

### PR DESCRIPTION
**Pull request by flayzer**
Simplified view of the console GenisysPro

### CODE REVIEW

**Comment by xISRAPILx** [comment]
please close it fastly!!! xd

**Comment by flayzer** [comment]
Eu, I came to help

**Comment by xISRAPILx** [comment]
@flayzer you came to kill me!!!

**Comment by TheAz928** [comment]
Bad pr, removing date from logger isn't good idea

**Comment by DerddyDert** [comment]
@TheAz928  if you get a chance would you review the other PRs as well?

**Comment by flayzer** [comment]
@TheAz928 It will do no harm + to this in the console will be less and more convenient message

**Comment by xISRAPILx** [comment]
This hides information about a lot. The name of the thread and so on ...

**Comment by TheAz928** [comment]
@flayzer It doesn't show the time, one necessary thing. Also thread type. Cleanness doesn't mean less message, cleanness means plain and good colored text

**Comment by flayzer** [comment]
@TheAz928 Right now I'll think about it and add 1 thing!

**Comment by TheAz928** [comment]
@flayzer Typo at your commit add date("H:i:s", $now), missing one "

**Pull request closed without merging**
