### PR TITLE
Bypass SpoonDetector xD

### PR DESCRIPTION
**Pull request by CortexPE**
### Notes:
Taken from a W.I.P. Build of Leveryl...
And get_calling_class() is from https://stackoverflow.com/a/6927569/7126351

### Purpose and Effect of This Pull Request
Bypass SpoonDetector

### Testing
1. Download the SpoonDetector Class from https://github.com/Falkirks/spoondetector/blob/master/src/spoondetector/SpoonDetector.php
2. Use the code below with a plugin:
```php
if(SpoonDetector::isThisSpoon()){
	SpoonDetector::printSpoon($this);
}
```
3. If it doesn't display the message and The plugin doesn't disable itself... It Worked! 😄

### CODE REVIEW

**Comment by HimbeersaftLP** [comment]
You don't get the point of SpoonDetector, do you?

**Comment by Sandertv** [comment]
I try to keep out from most of this spoon, I want nothing to do with it, but the only thing you achieve by bypassing that SpoonDetector is kiddos crying plugins don't work on plugin issue trackers. It's not like SpoonDetector prevents you from using it either. Just accept the terms and voila.

**Comment by CortexPE** [comment]
I know the point of it... It's just that *some* plugins (that has SpoonDetector on it) can run on spoons without any problems...

**Comment by HimbeersaftLP** [comment]
> I know the point of it... It's just that some plugins (that has SpoonDetector on it) can run on spoons without any problems...

And that's why there is an option to accept loading the plugin....

**Comment by CortexPE** [comment]
image
xd

**Comment by DerddyDert** [comment]
This isn't a spoon of PMMP anyways. @CortexPE seems to actually get the concept of open source and that's what's most important. Awesome breakdown of third party source used and credit given.

**Comment by DerddyDert** [comment]
@CortexPE thanks. Also @Sandertv your contribution to the conversations on GenisysPro is always welcome as you are very professional even if opinions differ. I'm locking this conversation as to many people haven't been handling their emotions on which server software is best and enough was said about this PR.

**Pull request merged**
