### PR TITLE
Small code cleanup

### PR DESCRIPTION
**Pull request by xISRAPILx**

### CODE REVIEW

**Comment by zKoz210** [comment]
omg, do not accept this

**Comment by erkam2002** [comment]
@zKoz210 why?

**Comment by zKoz210** [comment]
Because this is automatically generated documentation that is not needed. Also removes commented out code, which is still really needed

**Comment by Leo3418** [comment]
I'm closing this because of two denials and not-well-written description.

**Comment by DerddyDert** [comment]
Good call @Leo3418  @xISRAPILx maybe you can redo your PR? Change less and explain what you are doing?

**Comment by xISRAPILx** [comment]
Okey @DerddyDert

**Pull request closed without merging**
