### PR TITLE
Fix #741

### LINKED ISSUE #741: Crash..
GenisysPro Crash Dump Wed Aug 9 21:31:26 MSK 2017

Error: Object of class stdClass could not be converted to string
File: /src/pocketmine/Player
Line: 3225
Type: E_RECOVERABLE_ERROR

Code:
[3216] 				break;
[3217] 			case ProtocolInfo::COMMAND_STEP_PACKET:
[3218] 				if($this->spawned === false or !$this->isAlive()){
[3219] 					break;
[3220] 				}
[3221] 				$this->craftingType = 0;
[3222] 				$commandText = $packet->command;
[3223] 				if($packet->inputJson !== null){
[3224] 					foreach($packet->inputJson as $arg){ //command ordering will be an issue
[3225] 						$commandText .= " " . $arg;
[3226] 					}
[3227] 				}
[3228] 				$this->server->getPluginManager()->callEvent($ev = new PlayerCommandPreprocessEvent($this, "/" . $commandText));
[3229] 				if($ev->isCancelled()){
[3230] 					break;
[3231] 				}
[3232] 
[3233] 				Timings::$playerCommandTimer->startTiming();
[3234] 				$this->server->dispatchCommand($ev->getPlayer(), substr($ev->getMessage(), 1));
[3235] 				Timings::$playerCommandTimer->stopTiming();

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

GenisysPro version: 0000000000000000000000000000000000000000 [Protocol 113; API 3.0.1]
uname -a: Linux ih598876.vds.myihor.ru 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64
PHP version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Server uptime: 26 сек
Number of loaded worlds: 1
Players online: 18/1000

### PR DESCRIPTION
**Pull request by xISRAPILx**
Thanks, Sharov!

### Purpose and Effect of This Pull Request
Fix #741

### Testing
yes

### CODE REVIEW

**Comment by ivan691** [comment]
not work

**Comment by DerddyDert** [comment]
@ivan691 please explain. Does it crash the server or just not solve the issue?

**Comment by xISRAPILx** [comment]
check @ivan691 @DerddyDert 

It call a minet bots...

**Comment by Frago9876543210** [comment]
Subcommands not works

**Comment by xISRAPILx** [comment]
@DerddyDert open it...

**Pull request closed without merging**
