### PR TITLE
Trying fix error

### PR DESCRIPTION
**Pull request by NycuRO**
Warning: zlib_decode(): data error in /home/minecraft-pe-2/server/src/pocketmine/network/Network.php on line 274

### CODE REVIEW

**Comment by NycuRO** [comment]
Anyone can test them?

**Comment by DerddyDert** [comment]
Wow this would be a great one for @SuperXingKong  I hope he stops by...

**Comment by SuperXingKong** [comment]
# Here is a question: have you tested it?

**Comment by SuperXingKong** [comment]
Sorry I approved too early.
Don't merge it until confirmation.

**Comment by DerddyDert** [comment]
@SuperXingKong I'm confused

**Comment by DerddyDert** [comment]
@SuperXingKong did u see my discord message?

**Comment by SuperXingKong** [comment]
@DerddyDert I will read it. Wait a moment.

**Comment by Frago9876543210** [comment]
you tested it?

**Comment by xISRAPILx** [comment]
I think that it will help. @DerddyDert @SuperXingKong 
It just changes the type of the variable ... Sory, bad English =)

zlib_decode((string) $packet->payload, 1024 * 1024 * 64);

**Comment by xISRAPILx** [comment]
https://github.com/NycuRO/GenisysPro/pull/1 @NycuRO

**Comment by xISRAPILx** [comment]
#https://github.com/NycuRO/GenisysPro/pull/1

**Comment by xISRAPILx** [comment]
https://github.com/NycuRO/GenisysPro/pull/1 @NycuRO  @DerddyDert

**Comment by NycuRO** [comment]
I don't want help with this software because fucking false "mods" and fucking "devs" ,banned me on discord.

**Comment by DerddyDert** [comment]
Who banned you? I always see you in discord? Or are you talking about before when unprovoked, you keep telling everyone nonstop that Genisyspro is $hitty software with $hitty code and everyone is a fake dev and telling everyone not to use it and all that stuff? If that was the case it could have been because you jumped on board with the trolls and people were banning and kicking a lot to get rid of the unprofessional nonsense. idk Sorry your feelings got hurt man.

**Comment by NycuRO** [comment]
@DerddyDert Gabitzuu banned me. I'm talking the true, not others.

**Comment by xISRAPILx** [comment]
What? @NycuRO  PHP - easy language...

**Comment by NycuRO** [comment]
@xISRAPILx  ?

**Comment by xISRAPILx** [comment]
Why do you say that we do not know PHP? @NycuRO

**Comment by DerddyDert** [comment]
@xISRAPILx it was a private problem. He didnt talk about you. We solved the problem.

**Comment by DerddyDert** [comment]
@xISRAPILx can you test this now that it has your recommendations?

**Comment by xISRAPILx** [comment]
@DerddyDert don't have errors for it in my server

**Comment by xISRAPILx** [comment]
@DerddyDert There are no such errors on my server. I just suggested a more truthful option.

**Comment by xISRAPILx** [comment]
I think that you can merge @DerddyDert

**Comment by DerddyDert** [comment]
@SuperXingKong can you help clean this up? It's an old pr but he made another. Idk I'm confused..

**Comment by SuperXingKong** [comment]
ok

**Pull request closed without merging**
