### PR TITLE
Working sponge

### LINKED ISSUE #750: Sponge doesn't absorb water
screenshot_2017-08-09-23-22-12
And I have absorb-water to true

### PR DESCRIPTION
**Pull request by armagadon159753**
### Purpose and Effect of This Pull Request
update function absorbWater 

### Testing

Tested and approved^~^ for fix #750

### CODE REVIEW

**Comment by Frago9876543210** [comment]
@armagadon159753 Do not forget that this feature should be able to shutdown

**Comment by DerddyDert** [comment]
@Frago9876543210  please fix this yourself. Its your design.

**Comment by armagadon159753** [comment]
@Frago9876543210 This is not the case for me

**Comment by DerddyDert** [comment]
@armagadon159753 does this meet fragos requirements?

**Comment by xISRAPILx** [comment]
@armagadon159753 Give me permissions in you forkI want to supplement..

**Comment by Frago9876543210** [comment]
@DerddyDert I'll come on Monday and fix it.

**Comment by DerddyDert** [comment]
@Frago9876543210  ok, can you review other PRs? We are backed up

**Pull request closed without merging**
