### PR TITLE
Fix entity movement leak (URGENT)

### PR DESCRIPTION
**Pull request by Misteboss**
Work as intended for me, need to be merged asap !

### Purpose and Effect of This Pull Request
 
It fixes the movement leak when there is a lot of players online.
Optimised the perfs of my server by 20% (for me)

### Testing

Everything works, enjoy playing on a lag free server !

### CODE REVIEW

**Comment by ivan691** [comment]
Are you idiot ?

**Comment by Misteboss** [comment]
@Frago9876543210 need to be merged asap

**Comment by MasterOfTheRealm** [comment]
@Misteboss explain what your PR does and how it is useful.

"Work as intended for me, need to be merged asap !"
isn't much for us to review on

**Comment by Rateek** [comment]
wallah @ivan691 meme si tu parle pas français ta mere je la prend et je la ich ich sale pd c toi l'idiot bref toz dans ta mere et insulte pas les français de idiot alors que tu sais meme pas ce que sa veut dire switch($variable){ #FrenchArmy @Misteboss

**Comment by SolidRock2** [comment]
Wow it actually works. It also seems to fix the 'Steve moved wrongly!' issue. Nice PR.

**Comment by armagadon159753** [comment]
JPP @Rateek 👑

**Comment by Misteboss** [comment]
updated @MasterOfTheRealm

**Comment by ivan691** [comment]
It's not work.
Players can't move.

**Comment by Misteboss** [comment]
plugin issue :/ @ivan691

**Comment by ivan691** [comment]
No ! As soon as I changed it in the code and rebooted the server happened this problem. I have never had such a thing.

**Comment by SuperMaXAleX** [comment]
Everything is working fine for me

**Comment by Rateek** [comment]
@ivan691 wallah ferme ta gueule un peut tu sais rien faire je sais meme pas pq tu parle sale fils de pute apprend le php et après on se reparle 👍

**Comment by DerddyDert** [comment]
@ivan691 try to help them work out the issue that you observed please.

**Comment by DerddyDert** [comment]
@MasterOfTheRealm let's try to test and optimize this?

**Comment by bettydothings7** [comment]
I just test this with 10 players and noticed performance improvment too, i think we should merge

but I also get getName crash  (maybe related)
 
Error: Return value of pocketmine\Server::get_calling_class() must be of the type string, null returned
File: /src/pocketmine/Server
Line: 339
Type: notice

Code:
[330] 	}
[331] 	
[332] 	private function get_calling_class() : string {
[333] 		// tnx https://stackoverflow.com/a/6927569/7126351
[334] 		$trace = debug_backtrace();
[335] 		$class = $trace[1]['class'];
[336] 		for ( $i=1; $i<count( $trace ); $i++ ) {
[337] 			if ( isset( $trace[$i] ) )
[338] 				if ( $class != $trace[$i]['class'] )
[339] 					return $trace[$i]['class'];
[340] 		}
[341] 		return "null";
[342] 	}
[343] 
[344] 	/**
[345] 	 * @return bool
[346] 	 */
[347] 	public function isRunning(){
[348] 		return $this->isRunning === true;
[349] 	}

**Comment by Misteboss** [comment]
Your error is coming from a plugin, SpoonDetector.

**Comment by Misteboss** [comment]
We need a merge @MasterOfTheRealm !

**Comment by xISRAPILx** [comment]
@ivan691 Ты тупой, нет?

**Comment by DerddyDert** [comment]
@CortexPE awesome! Thanks. @ivan691 can you explain more on what issue this is causing? @MasterOfTheRealm have you tested this for errors?

**Comment by DerddyDert** [comment]
@Misteboss No variation of this pr works. Keep trying though its good to test stuff like this to make code more efficient. Thanks

**Pull request closed without merging**
