### PR TITLE
Core fixed

### PR DESCRIPTION
**Pull request by SuperXingKong**
### Description

Fixed bugs with the server.

### CODE REVIEW

**Comment by DerddyDert** [comment]
645PHP Parse error:  syntax error, unexpected 'usleep' (T_STRING) in ./src/pocketmine/PocketMine.php on line 476

**Comment by SuperXingKong** [comment]
Oops, will fix.

**Comment by DerddyDert** [comment]
Annnnd we're green

**Comment by SuperXingKong** [comment]
Yeah, I will merge it

**Pull request merged**
