### PR TITLE
add options to enable mob ai useing entitymanager plugin

### PR DESCRIPTION
**Pull request by djdisodo**
### Testing

sorry about dirty code and unused codes

### CODE REVIEW

**Comment by DerddyDert** [comment]
@djdisodo you will hear a lot of opinions about this PR.

**Comment by djdisodo** [comment]
........

**Comment by DerddyDert** [comment]
@djdisodo you gave up already? its a good idea. Lets see what others can do with it.

**Comment by djdisodo** [comment]
@DerddyDert I found a big error in it and now fixed

**Comment by BajanVlogs** [comment]
Ive tested this and it works good

**Comment by BajanVlogs** [comment]
But Zombies and Creepers do not drop stuff

**Comment by BajanVlogs** [comment]
Also Spawners dont work now Mobs drop the wrong things

**Comment by MasterOfTheRealm** [comment]
WTH is this... wow

**Comment by erkam2002** [comment]
@MasterOfTheRealm he try to copy entitymanager to genisyspro xD

**Comment by HimbeersaftLP** [comment]
lmao, I'd rather install a plugin than have it included in a phar just to take up more space (not that I would ever use GenisysPro anyways)

**Comment by djdisodo** [comment]
i dont think my pull is good how about get mob ai and some featured code from here?
https://github.com/BlueLightJapan/BlueLight

**Comment by djdisodo** [comment]
i dont think my pull is good how about get mob ai and some featured code from here?
https://github.com/BlueLightJapan/BlueLight

**Pull request closed without merging**
