### PR TITLE
lol.

### PR DESCRIPTION
**Pull request by xISRAPILx**
### Purpose and Effect of This Pull Request
Fix error:
[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\protocol\AnimatePacket::getVarLong()" (EXCEPTION) in "/src/pocketmine/network/protocol/AnimatePacket" at line 40

### CODE REVIEW

**Comment by MasterOfTheRealm** [comment]
you get a new error on line 52 then and even when that is fixed. there are a lots of warnings.

**Comment by xISRAPILx** [comment]
No, I have no mistakes, I do not have any problems with this.

In some, the team does not show, even after the issuance of rights. @MasterOfTheRealm

**Comment by MasterOfTheRealm** [comment]
`[Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\protocol\AnimatePacket::putVarLong()" (EXCEPTION) in "/src/pocketmine/network/protocol/AnimatePacket" at line 52
`

**Comment by xISRAPILx** [comment]
Oh @MasterOfTheRealm 

Yes, the putVarLong function does not exist.

**Comment by MasterOfTheRealm** [comment]
This won't really fix the problem completely so close for now

**Pull request closed without merging**
