### PR TITLE
1.1dev [Old API but stable]

### PR DESCRIPTION
**Pull request by SuperXingKong**

### CODE REVIEW

**Comment by DerddyDert** [comment]
@SuperXingKong There have been so many changes while you have been gone to make things more comparable with a wider range of plugin developers.. Namely adding src/pocketmine/network/mcpe/ among other things. When you make a statement like "GenisysPro needs a huge cleanup" but with a revert in mind, people don't realize it would undo so many fixes and added plugin comparability. Of course "cleanup" always sounds good so most will agree. 

What we need to do is to start from where we are now and focus on a rewrite so we can get GenisysPro working with MCPE 1.2. Then from there we focus on stability. Please talk with the lead devs in Discord so we can approach this the best way and from the same approach.

**Comment by SuperKali** [comment]
@SuperXingKong GenisysPro is stable version actually, not revert please, I have 50 playes online and 20% of load and 20TPS of 10/20%

**Comment by DerddyDert** [comment]
@SuperXingKong @SuperKali I spoke with @CortexPE and he will make a patch that makes things backwards compatible for the old API. the addition of /mcpe/ folder wont matter in plugins and they can be written with or without it once the patch is done.

**Comment by CortexPE** [comment]
I'm planning to mirror EVERY SINGLE packet on the new folder structure to the old one....
Just like symlink on linux.

Hacky? Yes. IT'S VERY HACKY. xD

The main goal of it is so that the Chinese plugin developer community and @SuperXingKong can still use old plugins :)

**Comment by TDMidkwhatisxd** [comment]
Its easy to revert stuff than update to 1.2 !!!
---------------------------------------------
Now its SPOON WARS, all spoons try to update to a stable 1.2, some are dead.
Other spoons, just copy/paste from pmmp then rename ^^ , how I know? Crafting on classic UI don't work, wich is a PMMP signature glitch.

I wonder if this software will be updated to 1.2 , or will wait for a spoon to update to can copypasta.
This pr is useless. I don't know why its there.


From my point of view is cringy and childish. Rather than doing some real stuff, lets revert to FUKKIT ^^.
0 lags 0 problems.

**Comment by erkam2002** [comment]
This will remove all new function -.- plugins will not work more.. everyone needs to rewrite something.

#Please dont Revert

**Comment by CortexPE** [comment]
@SuperXingKong Take a look at #1097 ...
And if that works / Fixes your problem, Please consider closing this PR.

**Comment by SuperXingKong** [comment]
Ok. But #1097 is useless... Old plugins still not work.

**Pull request closed without merging**
