### PR TITLE
Fix DisconnectPacket (message) #205

### PR DESCRIPTION
**Pull request by RateekMCPE**
It's done, is tested !

### CODE REVIEW

**Comment by SuperKali** [comment]
i have test not work

**Comment by SuperKali** [comment]
https://youtu.be/NUecyOXhBkc

**Comment by SuperXingKong** [comment]
@DerddyDert Could you help test it?

**Comment by Prisane** [comment]
Yes it does not work

**Comment by caspervanneck** [comment]
@RateekMCPE it dont work buy a better host or wifi or pc

**Comment by caspervanneck** [comment]
its 1 of those

**Comment by Prisane** [comment]
@caspervanneck This is not related to a pc or wifi or host.

**Comment by caspervanneck** [comment]
@Prisane okey why does it for me work
???

**Comment by Prisane** [comment]
@caspervanneck All players on the my server do not work. Will anyone buy a new phone or host?

**Comment by Prisane** [comment]
And now you closed this pull request. It is very comic. It doesn't even work properly!

**Comment by RateekMCPE** [comment]
In fact it works 1 times out of 2 helped me a lot

**Comment by DerddyDert** [comment]
I cannot recreate this problem. I have never seen such a split decision. Right down the middle. Lets try this. **Does this pull request CAUSE a problem** f## or those of you who say it works already without this pull? @RateekMCPE @Prisane @SuperXingKong @caspervanneck @SuperKali

**Comment by Prisane** [comment]
It's not clear what the main problem is. I did a lot of testing with my team. When there are more than 2 players. Disconnect Packet is not working. So Player 1, shows kick message but Player 2 also says "Disconnected from server". I think it does not solve the problem and it is not a temporary method. PMMP has out solve this problem, but I do not think anyone else will solve this problem. Maybe if we focus this problem it... @DerddyDert

**Comment by DerddyDert** [comment]
Needs more evidence to support as a fix..

**Pull request closed without merging**
