### PR TITLE
[#WIP] Start Improvment Generator + Test New Reformat

### PR DESCRIPTION
**Pull request by NycuRO**
This PR is created for Improvment Generator and get More Performance.
Please not close this PR if not work, i'll fix.

@DerddyDert Thanks for get me down of rank "Developer" on Discord because shitty Developers like that.
Probably you don't know who get improvment of new generaion on Nukkit: Nukkit/Nukkit#1250
And pull where is accepted: Nukkit/Nukkit#1416

### CODE REVIEW

**Comment by NycuRO** [comment]
@Pizzahaet Lmao, it's one WIP.

**Comment by Pizzahaet** [comment]
I am just trying to get removed from this god forsaking org, no one here can code, everything here is from Tesseract

**Comment by NycuRO** [comment]
@Pizzahaet Lol

**Comment by NycuRO** [comment]
@Pizzahaet Probably you don't know who get improvment of new generaion on Nukkit: https://github.com/Nukkit/Nukkit/pull/1250

**Comment by NycuRO** [comment]
And pull where is accepted: https://github.com/Nukkit/Nukkit/pull/1416

**Comment by NycuRO** [comment]
I'm start continuing these PR on wekeend, i don't have time now.

**Comment by MasterOfTheRealm** [comment]
YASSS GOOD LUCK! Nycu!

**Comment by DerddyDert** [comment]
@NycuRO  I'm closing this. @Frago9876543210 can you help him make a generator branch?

**Pull request closed without merging**
