### PR TITLE
Added LevelSounds coming from client

### PR DESCRIPTION
**Pull request by EmreTr1**
### Purpose and Effect of This Pull Request

Added Level spunds coming from mcpe client
### Testing

Tested and working

### CODE REVIEW

**Comment by larryTheCoder** [comment]
Uh sounds not spunds xD

**Comment by EmreTr1** [comment]
this working :D

**Comment by MasterOfTheRealm** [comment]
@EmreTr1 For what sounds exactly?

**Comment by EmreTr1** [comment]
@MasterOfTheRealm exam: entity hurt sound

**Comment by larryTheCoder** [comment]
Accepted

**Comment by DerddyDert** [comment]
@EmreTr1 which sounds did this add? Only the one sound? Does lightning work with it?

**Comment by EmreTr1** [comment]
@DerddyDert not one sound. Block punch sound entity punch sound... 
i have not testwd lightning sound

**Comment by EmreTr1** [comment]
There is also this pmmp

**Comment by EmreTr1** [comment]
I think it adds all LevelEventSounds automatically

**Comment by DerddyDert** [comment]
@Frago9876543210  you check this one yet?

**Pull request merged**
