### PR TITLE
Added ServerShutdownEvent

### PR DESCRIPTION
**Pull request by XFuryMCPE**
### Purpose and Effect of This Pull Request

Calls event when the server shuts down from a command or pluginwise, which can be cancelled.

### Testing

This has been tested.

### CODE REVIEW

**Comment by XFuryMCPE** [comment]
:D

**Comment by MasterOfTheRealm** [comment]
Look good!!! Nice work!

**Comment by XFuryMCPE** [comment]
Thank you!

**Comment by pmmp-bot2** [comment]
<----------

START INJECTING

SPAM BOT SPAM BOT SPAM BOT SPAM BOTSPAM BOT
SPAM BOT SPAM BOT SPAM BOT SPAM BOT SPAM BOT
->>>>>>>>>>>>>>>>>>>

**Comment by pmmp-bot2** [comment]
<----------

START INJECTING

SPAM BOT SPAM BOT SPAM BOT SPAM BOTSPAM BOT
SPAM BOT SPAM BOT SPAM BOT SPAM BOT SPAM BOT
->>>>>>>>>>>>>>>>>>>

**Comment by pmmp-bot2** [comment]
<----------

START INJECTING

SPAM BOT SPAM BOT SPAM BOT SPAM BOTSPAM BOT
SPAM BOT SPAM BOT SPAM BOT SPAM BOT SPAM BOT
->>>>>>>>>>>>>>>>>>>

**Comment by pmmp-bot2** [comment]
<----------

START INJECTING

SPAM BOT SPAM BOT SPAM BOT SPAM BOTSPAM BOT
SPAM BOT SPAM BOT SPAM BOT SPAM BOT SPAM BOT
->>>>>>>>>>>>>>>>>>>

**Comment by pmmp-bot2** [comment]
<----------

START INJECTING

SPAM BOT SPAM BOT SPAM BOT SPAM BOTSPAM BOT
SPAM BOT SPAM BOT SPAM BOT SPAM BOT SPAM BOT
->>>>>>>>>>>>>>>>>>>

**Comment by pmmp-bot2** [comment]
<----------

START INJECTING

SPAM BOT SPAM BOT SPAM BOT SPAM BOTSPAM BOT
SPAM BOT SPAM BOT SPAM BOT SPAM BOT SPAM BOT
->>>>>>>>>>>>>>>>>>>

**Comment by pmmp-bot2** [comment]
<----------

START INJECTING

SPAM BOT SPAM BOT SPAM BOT SPAM BOTSPAM BOT
SPAM BOT SPAM BOT SPAM BOT SPAM BOT SPAM BOT
->>>>>>>>>>>>>>>>>>>

**Comment by erkam2002** [comment]
???

**Comment by DerddyDert** [comment]
Hahaha what happened?

**Comment by MasterOfTheRealm** [comment]
idk maybe some enchancements?

**Pull request closed without merging**
