### PR TITLE
Added transfer function

### PR DESCRIPTION
**Pull request by erkam2002**

### CODE REVIEW

**Comment by erkam2002** [comment]
Merge this

**Comment by SuperXingKong** [comment]
Well, just need a little addtion. I will push here

**Comment by DerddyDert** [comment]
@SuperXingKong conflicts in player.PHP because it was just updated?

**Comment by SuperXingKong** [comment]
idk..Strangely...(ﾟ⊿ﾟ)ﾂ

**Comment by DerddyDert** [comment]
@SuperXingKong yes, if you don't know then its strange... Hehe

**Comment by SuperXingKong** [comment]
Sorry >_<

**Comment by SuperXingKong** [comment]
Sorry >_<

**Comment by DerddyDert** [comment]
Sorry, it wasn't your fault @erkam2002

**Pull request closed without merging**
