### PR TITLE
 It call bug, when in command not permissions

### PR DESCRIPTION
**Pull request by xISRAPILx**

### CODE REVIEW

**Comment by DerddyDert** [comment]
@xISRAPILx  can you explain why you want this change more clearly please?

**Comment by xISRAPILx** [comment]
If the command is made in the oncommand - it will not be available, because there is no setPermission @DerddyDert

**Comment by xISRAPILx** [comment]
give me more permissions, pls @DerddyDert I think I deserve it.

**Comment by flayzer** [comment]
годнота

**Comment by xISRAPILx** [comment]
@flayzer хуета

**Comment by NycuRO** [comment]
It's ok man.

**Comment by xISRAPILx** [comment]
@NycuRO Yep, i good boy =)

**Comment by xISRAPILx** [comment]
@DerddyDert @Frago9876543210 @SuperXingKong merge it fastly!

**Pull request merged**
