### PR TITLE
Migrate from the old Genisys packet structure to the PMMP one

### PR DESCRIPTION
**Pull request by CortexPE**
### Purpose and Effect of This Pull Request
Long story short, this basically just migrates packets from the old Genisys packet structure to the PMMP Packet structure.

### Testing
Go in-game.

### CODE REVIEW

**Comment by CortexPE** [comment]
lemme update Info.php -> ProtocolInfo.php as well.

**Comment by DerddyDert** [comment]
@CortexPE That's a lot of work man! We need to revert some things first. Thanks!

**Comment by CortexPE** [comment]
told ya sometimes ReplaceTool doesnt work
xD
I was about to update ProtocolInfo.php as well
image

**Comment by xISRAPILx** [comment]
use it
[Advanced Find and Replace 7.zip](https://github.com/GenisysPro/GenisysPro/files/1227466/Advanced.Find.and.Replace.7.zip)

**Comment by CortexPE** [comment]
Finally done!

**Comment by DerddyDert** [comment]
I dont think this is from your changes @CortexPE but when using this src and when placing any block:

[08:59:53] [Server thread/DEBUG]: BatchPacket  0x78da63d66162525776707cc1c4c4c4a0e16dcfc0d060cf106160f7f59cb053a16dbb93e5141367068e064606206006aa6556646100001d9709db
[08:59:53] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\protocol\AnimatePacket::getVarLong()" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/AnimatePacket" at line 40
[08:59:53] [Server thread/DEBUG]: #0 /src/pocketmine/Player(2365): pocketmine\network\Network->processBatch(pocketmine\network\mcpe\protocol\BatchPacket object, pocketmine\Player Player(1))
[08:59:53] [Server thread/DEBUG]: #1 /src/pocketmine/network/mcpe/RakLibInterface(173): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[08:59:53] [Server thread/DEBUG]: #2 /src/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 72.84.106.241:58720, raklib\protocol\EncapsulatedPacket `..f..c....x.c.abRWvp|......m...`..a`....S.m.....g...F. `..eVda......, integer 0)
[08:59:53] [Server thread/DEBUG]: #3 /src/pocketmine/network/mcpe/RakLibInterface(89): raklib\server\ServerHandler->handlePacket(boolean)
[08:59:53] [Server thread/DEBUG]: #4 /src/pocketmine/network/Network(190): pocketmine\network\mcpe\RakLibInterface->process(boolean)
[08:59:53] [Server thread/DEBUG]: #5 /src/pocketmine/Server(2814): pocketmine\network\Network->processInterfaces(boolean)
[08:59:53] [Server thread/DEBUG]: #6 /src/pocketmine/Server(2546): pocketmine\Server->tick(boolean)
[08:59:53] [Server thread/DEBUG]: #7 /src/pocketmine/Server(2424): pocketmine\Server->tickProcessor(boolean)
[08:59:53] [Server thread/DEBUG]: #8 /src/pocketmine/Server(1995): pocketmine\Server->start(boolean)
[08:59:53] [Server thread/DEBUG]: #9 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/genpro/, string /home/genpro/, string /home/genpro/plugins/)

**Comment by DerddyDert** [comment]
@MasterOfTheRealm see above please

**Comment by DerddyDert** [comment]
Also I couldn't place any mobs...

**Comment by CortexPE** [comment]
> I dont think this is from your changes @CortexPE but when using this src and when placing any block:
```
[08:59:53] [Server thread/DEBUG]: BatchPacket 0x78da63d66162525776707cc1c4c4c4a0e16dcfc0d060cf106160f7f59cb053a16dbb93e5141367068e064606206006aa6556646100001d9709db
[08:59:53] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\network\mcpe\protocol\AnimatePacket::getVarLong()" (EXCEPTION) in "/src/pocketmine/network/mcpe/protocol/AnimatePacket" at line 40
[08:59:53] [Server thread/DEBUG]: #0 /src/pocketmine/Player(2365): pocketmine\network\Network->processBatch(pocketmine\network\mcpe\protocol\BatchPacket object, pocketmine\Player Player(1))
[08:59:53] [Server thread/DEBUG]: #1 /src/pocketmine/network/mcpe/RakLibInterface(173): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
[08:59:53] [Server thread/DEBUG]: #2 /src/raklib/server/ServerHandler(99): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 72.84.106.241:58720, raklib\protocol\EncapsulatedPacket ..f..c....x.c.abRWvp|......m.....a....S.m.....g...F...eVda......, integer 0)
[08:59:53] [Server thread/DEBUG]: #3 /src/pocketmine/network/mcpe/RakLibInterface(89): raklib\server\ServerHandler->handlePacket(boolean)
[08:59:53] [Server thread/DEBUG]: #4 /src/pocketmine/network/Network(190): pocketmine\network\mcpe\RakLibInterface->process(boolean)
[08:59:53] [Server thread/DEBUG]: #5 /src/pocketmine/Server(2814): pocketmine\network\Network->processInterfaces(boolean)
[08:59:53] [Server thread/DEBUG]: #6 /src/pocketmine/Server(2546): pocketmine\Server->tick(boolean)
[08:59:53] [Server thread/DEBUG]: #7 /src/pocketmine/Server(2424): pocketmine\Server->tickProcessor(boolean)
[08:59:53] [Server thread/DEBUG]: #8 /src/pocketmine/Server(1995): pocketmine\Server->start(boolean)
[08:59:53] [Server thread/DEBUG]: #9 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/genpro/, string /home/genpro/, string /home/genpro/plugins/)
```
<hr />
Probably...
Because, I didn't change anything...
I just changed the namespaces and ClassNames

**Comment by DerddyDert** [comment]
@CortexPE right. We need to fix that error though..

**Comment by MasterOfTheRealm** [comment]
This isnt Cortex's fault...its the Animate Packet that was badly handled by us. Fix that and everything works fine.

**Comment by DerddyDert** [comment]
Testing fix with this pr now

**Comment by SuperKali** [comment]
But because you're ruining a version transforming it into pmmp

**Comment by DerddyDert** [comment]
Everything seems to work great with no console activity. screenshot_20170816-053438

**Comment by DerddyDert** [comment]
@SuperKali this only changes a folder.

**Comment by MasterOfTheRealm** [comment]
@SuperKali nothing of the original GensiysPro code is changed. just the folder structure. plus the packets change all the time

**Pull request merged**
